version: '3.7'

services:
  todo-app-backend:
    container_name: todo-app-backend
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: base
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo-app-develop
      CORS_ALLOW_ORIGIN: http://localhost:8082
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    tty: true

  db:
    container_name: todo-app-db
    image: mysql:8.0.13
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app_db
    ports:
      - 3333:3306
    tty: true